export const CLIENT = "CLIENT";
export const REALTOR = "REALTOR";

export const TOAST_GREEN = "#2E7D31";
export const TOAST_RED = "#D3302F";
export const TOAST_YELLOW = "#ED6C03";
export const TOAST_BLUE = "#0088D1";

export const NAV_HEIGHT = "90px";
export const BODY_WIDTH_LG = "1400px";
export const BODY_WIDTH_SMALL = "900px";
export const WHITE_CARD_HOVER = "#c9c9c9";

export const ERROR_RED = "#D3302F";
export const BLACK_FONT = "#333333";

export const NEUTRAL_GREY_600 = "#0F172A";
export const NEUTRAL_GREY_400 = "#94A3B8";
export const NEUTRAL_GREY_50 = "#F8FAFC";

export const PRIMARY_BLUE_500 = "#1D4ED8;";
export const PRIMARY_BLUE_300 = "#6183E4";

export const EXTERNAL_LINK_BLUE = "#1D4ED8";

export const TOAST_COLOR_MAP = {
  success: TOAST_GREEN,
  error: TOAST_RED,
  warning: TOAST_YELLOW,
  info: TOAST_BLUE,
};

export const PAIKKAKUNNAT = [
  "Akaa",
  "Alajärvi",
  "Alavieska",
  "Alavus",
  "Asikkala",
  "Askola",
  "Aura",
  "Brändö",
  "Eckerö",
  "Enonkoski",
  "Enontekiö",
  "Espoo",
  "Eura",
  "Eurajoki",
  "Evijärvi",
  "Finström",
  "Forssa",
  "Föglö",
  "Geta",
  "Haapajärvi",
  "Haapavesi",
  "Hailuoto",
  "Halsua",
  "Hamina",
  "Hammarland",
  "Hankasalmi",
  "Hanko",
  "Harjavalta",
  "Hartola",
  "Hattula",
  "Hausjärvi",
  "Heinola",
  "Heinävesi",
  "Helsinki",
  "Hirvensalmi",
  "Hollola",
  "Huittinen",
  "Humppila",
  "Hyrynsalmi",
  "Hyvinkää",
  "Hämeenkyrö",
  "Hämeenlinna",
  "Ii",
  "Iisalmi",
  "Iitti",
  "Ikaalinen",
  "Ilmajoki",
  "Ilomantsi",
  "Imatra",
  "Inari",
  "Inkoo",
  "Isojoki",
  "Isokyrö",
  "Janakkala",
  "Joensuu",
  "Jokioinen",
  "Jomala",
  "Joroinen",
  "Joutsa",
  "Juuka",
  "Juupajoki",
  "Juva",
  "Jyväskylä",
  "Jämijärvi",
  "Jämsä",
  "Järvenpää",
  "Kaarina",
  "Kaavi",
  "Kajaani",
  "Kalajoki",
  "Kangasala",
  "Kangasniemi",
  "Kankaanpää",
  "Kannonkoski",
  "Kannus",
  "Karijoki",
  "Karkkila",
  "Karstula",
  "Karvia",
  "Kaskinen",
  "Kauhajoki",
  "Kauhava",
  "Kauniainen",
  "Kaustinen",
  "Keitele",
  "Kemi",
  "Kemijärvi",
  "Keminmaa",
  "Kemiönsaari",
  "Kempele",
  "Kerava",
  "Keuruu",
  "Kihniö",
  "Kinnula",
  "Kirkkonummi",
  "Kitee",
  "Kittilä",
  "Kiuruvesi",
  "Kivijärvi",
  "Kokemäki",
  "Kokkola",
  "Kolari",
  "Konnevesi",
  "Kontiolahti",
  "Korsnäs",
  "Koski Tl",
  "Kotka",
  "Kouvola",
  "Kristiinankaupunki",
  "Kruunupyy",
  "Kuhmo",
  "Kuhmoinen",
  "Kumlinge",
  "Kuopio",
  "Kuortane",
  "Kurikka",
  "Kustavi",
  "Kuusamo",
  "Kyyjärvi",
  "Kärkölä",
  "Kärsämäki",
  "Kökar",
  "Lahti",
  "Laihia",
  "Laitila",
  "Lapinjärvi",
  "Lapinlahti",
  "Lappajärvi",
  "Lappeenranta",
  "Lapua",
  "Laukaa",
  "Lemi",
  "Lemland",
  "Lempäälä",
  "Leppävirta",
  "Lestijärvi",
  "Lieksa",
  "Lieto",
  "Liminka",
  "Liperi",
  "Lohja",
  "Loimaa",
  "Loppi",
  "Loviisa",
  "Luhanka",
  "Lumijoki",
  "Lumparland",
  "Luoto",
  "Luumäki",
  "Maalahti",
  "Maarianhamina - Mariehamn",
  "Marttila",
  "Masku",
  "Merijärvi",
  "Merikarvia",
  "Miehikkälä",
  "Mikkeli",
  "Muhos",
  "Multia",
  "Muonio",
  "Mustasaari",
  "Muurame",
  "Mynämäki",
  "Myrskylä",
  "Mäntsälä",
  "Mänttä-Vilppula",
  "Mäntyharju",
  "Naantali",
  "Nakkila",
  "Nivala",
  "Nokia",
  "Nousiainen",
  "Nurmes",
  "Nurmijärvi",
  "Närpiö",
  "Orimattila",
  "Oripää",
  "Orivesi",
  "Oulainen",
  "Oulu",
  "Outokumpu",
  "Padasjoki",
  "Paimio",
  "Paltamo",
  "Parainen",
  "Parikkala",
  "Parkano",
  "Pedersören kunta",
  "Pelkosenniemi",
  "Pello",
  "Perho",
  "Pertunmaa",
  "Petäjävesi",
  "Pieksämäki",
  "Pielavesi",
  "Pietarsaari",
  "Pihtipudas",
  "Pirkkala",
  "Polvijärvi",
  "Pomarkku",
  "Pori",
  "Pornainen",
  "Porvoo",
  "Posio",
  "Pudasjärvi",
  "Pukkila",
  "Punkalaidun",
  "Puolanka",
  "Puumala",
  "Pyhtää",
  "Pyhäjoki",
  "Pyhäjärvi",
  "Pyhäntä",
  "Pyhäranta",
  "Pälkäne",
  "Pöytyä",
  "Raahe",
  "Raasepori",
  "Raisio",
  "Rantasalmi",
  "Ranua",
  "Rauma",
  "Rautalampi",
  "Rautavaara",
  "Rautjärvi",
  "Reisjärvi",
  "Riihimäki",
  "Ristijärvi",
  "Rovaniemi",
  "Ruokolahti",
  "Ruovesi",
  "Rusko",
  "Rääkkylä",
  "Saarijärvi",
  "Salla",
  "Salo",
  "Saltvik",
  "Sastamala",
  "Sauvo",
  "Savitaipale",
  "Savonlinna",
  "Savukoski",
  "Seinäjoki",
  "Sievi",
  "Siikainen",
  "Siikajoki",
  "Siikalatva",
  "Siilinjärvi",
  "Simo",
  "Sipoo",
  "Siuntio",
  "Sodankylä",
  "Soini",
  "Somero",
  "Sonkajärvi",
  "Sotkamo",
  "Sottunga",
  "Sulkava",
  "Sund",
  "Suomussalmi",
  "Suonenjoki",
  "Sysmä",
  "Säkylä",
  "Taipalsaari",
  "Taivalkoski",
  "Taivassalo",
  "Tammela",
  "Tampere",
  "Tervo",
  "Tervola",
  "Teuva",
  "Tohmajärvi",
  "Toholampi",
  "Toivakka",
  "Tornio",
  "Turku",
  "Tuusniemi",
  "Tuusula",
  "Tyrnävä",
  "Ulvila",
  "Urjala",
  "Utajärvi",
  "Utsjoki",
  "Uurainen",
  "Uusikaarlepyy",
  "Uusikaupunki",
  "Vaala",
  "Vaasa",
  "Valkeakoski",
  "Vantaa",
  "Varkaus",
  "Vehmaa",
  "Vesanto",
  "Vesilahti",
  "Veteli",
  "Vieremä",
  "Vihti",
  "Viitasaari",
  "Vimpeli",
  "Virolahti",
  "Virrat",
  "Vårdö",
  "Vöyri",
  "Ylitornio",
  "Ylivieska",
  "Ylöjärvi",
  "Ypäjä",
  "Ähtäri",
  "Äänekoski",
];
